<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Pb.Cli</RootNamespace>
    <AssemblyName>bridge</AssemblyName>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Pb.Core/Pb.Core.csproj" />
  </ItemGroup>

</Project>
